import Head from 'next/head';
import DesignHeader from '../components/DesignHeader';
import design from '../data/designData';
import DesignCards from '../components/DesignCards';
import cards from '../data/designCardData';
import DesignSection from '../components/DesignSection';

export default function AppDesign() {
  const cardArray = [];
  for (let key in cards) {
    if (cards.hasOwnProperty(key)) {
      let value = cards[key];
      if (key != 'app') cardArray.push(value);
    }
  }
  return (
    <>
      <Head>
        <title>Frontend Mentor | Designo Agency Website Challenge</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <DesignHeader page={design.app} />
      <DesignSection page={design.app} />
      <DesignCards cards={cardArray} />
    </>
  );
}
