import Head from 'next/head';
import Info from '../components/Info';
import countries from '../data/countriesInfo';
import contactSection from '../data/contactData';
import ContactCard from '../components/ContactCard';

export default function Contact() {
  return (
    <>
      <Head>
        <title>Frontend Mentor | Designo Agency Website Challenge</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <ContactCard section={contactSection[0]} />
      <Info sections={countries} page={'contact'} />
    </>
  );
}
