import Head from 'next/head';
import Info from '../components/Info';
import countries from '../data/countriesInfo';

export default function Contact() {
  return (
    <>
      <Head>
        <title>Frontend Mentor | Designo Agency Website Challenge</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Info sections={countries} page={'contact'} />
    </>
  );
}
