import Head from 'next/head';
import Header from '../components/Header';
import Navbar from '../components/Navbar';
import Footer from '../components/Footer';
import Main from '../components/Main';
import Info from '../components/Info';
import ProjectQuery from '../components/ProjectQuery';
import DesignCards from '../components/DesignCards';

export default function Home() {
  return (
    <>
      <Head>
        <title>Frontend Mentor | Designo Agency Website Challenge</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Navbar></Navbar>
      <Main></Main>
      <DesignCards></DesignCards>
      <Info></Info>
      <ProjectQuery></ProjectQuery>
      <Footer></Footer>
    </>
  );
}
