import Head from 'next/head';

export default function Home() {
  return (
    <div>
      <Head>
        <title>Frontend Mentor | Designo Agency Website Challenge</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main>
        <section className='bg-blue-500 min-h-screen flex'>
          <h1>hello</h1>
        </section>
      </main>
    </div>
  );
}
